name: mailer.v1
listenOn: 0.0.0.0:3007
timeout: 0
health: false

log:
  mode: console
  level: info
  stat: false

middlewares:
  stat: false

mailer:
  provider: smtp
  from: "Cordis <no-reply@cordis.localhost>"
  passwordResetURL: "${CORDIS_PASSWORD_RESET_URL}"
  emailVerificationURL: "${CORDIS_EMAIL_VERIFICATION_URL}"
  smtp:
    address: mailpit:1025
    requireTLS: false
    timeout: 10s
