name: dispatcher.v1

log:
  level: error
  stat: false

kafka:
  seeds:
    - 127.0.0.1:9092
  guildTopic: cordis.guild.events.v1
  messageTopic: message.events
  consumerGroup: cordis.dispatcher.v1

redis:
  host: 127.0.0.1:6379
  type: node

dispatcher:
  dispatchTimeoutSeconds: 5
  retryMinMilliseconds: 100
  retryMaxSeconds: 5
